@startuml

' skinparam maxMessageSize 150
skinparam actorStyle awesome

actor OGCWMTSClientSeed as "OGC WMTS Client (Seed)"
actor OGCWMTSClientLeech as "OGC WMTS Client (Leech)"
participant OGCWMTServer as "OGC WMT Service"
participant TorrentServer as "Torrent Server"

== Fetching And Seeding the Tile ==

OGCWMTSClientSeed -> OGCWMTServer : Requesting the tile
activate OGCWMTSClientSeed
activate OGCWMTServer
OGCWMTServer --> OGCWMTSClientSeed : Data
deactivate OGCWMTServer
OGCWMTSClientSeed -> TorrentServer : Seeding the region
activate TorrentServer
TorrentServer --> OGCWMTSClientSeed : OK
deactivate TorrentServer
deactivate OGCWMTSClientSeed

== Leeching the Region ==

group Requesting Region Seed 

OGCWMTSClientLeech -> TorrentServer : Requesting region
activate OGCWMTSClientLeech
activate TorrentServer
TorrentServer --> OGCWMTSClientLeech : OK, there is a seed

end

group WebRTC Signaling

TorrentServer -> OGCWMTSClientSeed : Requesting WebRTC offer
activate OGCWMTSClientSeed
OGCWMTSClientSeed --> TorrentServer : WebRTC offer (Seed)
TorrentServer -> OGCWMTSClientLeech : WebRTC offer (Seed)
OGCWMTSClientLeech --> TorrentServer : WebRTC offer (Leech)
TorrentServer ->  OGCWMTSClientSeed : WebRTC offer (Leech)
deactivate TorrentServer
OGCWMTSClientLeech <-> OGCWMTSClientSeed : ICE candidates checking

end

group Data Transmitting

OGCWMTSClientSeed -> OGCWMTSClientSeed : Archiving tiles for the requested region 
OGCWMTSClientSeed -> OGCWMTSClientLeech : Binary data
deactivate OGCWMTSClientLeech
deactivate OGCWMTSClientSeed

end

@enduml
